<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class OthersCurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['name' => 'Afghanistan Afghani', 'code' => 'AFN', 'rate' => 67.271, 'symbol' => '؋', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Albania Lek', 'code' => 'ALL', 'rate' => 91.47, 'symbol' => 'L', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Algerian Dinar', 'code' => 'DZD', 'rate' => 133.08, 'symbol' => 'دج', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Angolan Kwanza', 'code' => 'AOA', 'rate' => 910.982, 'symbol' => 'Kz', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Argentine Peso', 'code' => 'ARS', 'rate' => 1007.685, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Armenian Dram', 'code' => 'AMD', 'rate' => 389.25, 'symbol' => '֏', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Aruban Guilder', 'code' => 'AWG', 'rate' => 1.79, 'symbol' => 'ƒ', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Australian Dollar', 'code' => 'AUD', 'rate' => 1.54, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Azerbaijan Manat', 'code' => 'AZN', 'rate' => 1.699, 'symbol' => '₼', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bahamian Dollar', 'code' => 'BSD', 'rate' => 1, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bahraini Dinar', 'code' => 'BHD', 'rate' => 0.377, 'symbol' => '.د.ب', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Barbados Dollar', 'code' => 'BBD', 'rate' => 2, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Belarusian Ruble', 'code' => 'BYN', 'rate' => 3.427, 'symbol' => 'Br', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Belize Dollar', 'code' => 'BZD', 'rate' => 2, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bermuda Dollar', 'code' => 'BMD', 'rate' => 1, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bhutan Ngultrum', 'code' => 'BTN', 'rate' => 84.45, 'symbol' => 'Nu.', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bolivia Boliviano', 'code' => 'BOB', 'rate' => 6.857, 'symbol' => 'Bs.', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bosnia and Herzegovina Convertible Mark', 'code' => 'BAM', 'rate' => 1.854, 'symbol' => 'KM', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Botswana Pula', 'code' => 'BWP', 'rate' => 13.55, 'symbol' => 'P', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Brazilian Real', 'code' => 'BRL', 'rate' => 5.817, 'symbol' => 'R$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Brunei Dollar', 'code' => 'BND', 'rate' => 1.342, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bulgarian Lev', 'code' => 'BGN', 'rate' => 1.854, 'symbol' => 'лв', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Burundi Franc', 'code' => 'BIF', 'rate' => 2885.728, 'symbol' => 'FBu', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Cambodian Riel', 'code' => 'KHR', 'rate' => 4017, 'symbol' => '៛', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Canadian Dollar', 'code' => 'CAD', 'rate' => 1.405, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Cape Verde Escudo', 'code' => 'CVE', 'rate' => 104.497, 'symbol' => '$', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Cayman Is. Dollar', 'code' => 'KYD', 'rate' => 0.82, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Chilean Peso', 'code' => 'CLP', 'rate' => 973, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Chinese Renminbi', 'code' => 'CNY', 'rate' => 7.245, 'symbol' => '¥', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Colombian Peso', 'code' => 'COP', 'rate' => 4413, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Comoros Franc', 'code' => 'KMF', 'rate' => 466.232, 'symbol' => 'CF', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Congo Franc, Dem. Rep.of', 'code' => 'CDF', 'rate' => 2843.075, 'symbol' => 'FC', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Costa Rica Colon', 'code' => 'CRC', 'rate' => 509.02, 'symbol' => '₡', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Cuban Peso', 'code' => 'CUP', 'rate' => 24, 'symbol' => '₱', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Czech Koruna', 'code' => 'CZK', 'rate' => 23.97, 'symbol' => 'Kč', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Danish Krone', 'code' => 'DKK', 'rate' => 7.068, 'symbol' => 'kr', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Djibouti Francs', 'code' => 'DJF', 'rate' => 177, 'symbol' => 'Fdj', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'E.C. Dollar', 'code' => 'XCD', 'rate' => 2.7, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Dominican Peso', 'code' => 'DOP', 'rate' => 60.167, 'symbol' => 'RD$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Egyptian Pound', 'code' => 'EGP', 'rate' => 49.61, 'symbol' => '£', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Eritrea Nakfa', 'code' => 'ERN', 'rate' => 15, 'symbol' => 'Nfk', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Lilangeni', 'code' => 'SZL', 'rate' => 18.155, 'symbol' => 'E', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Ethiopian Birr', 'code' => 'ETB', 'rate' => 121.808, 'symbol' => 'Br', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Fiji Dollar', 'code' => 'FJD', 'rate' => 2.25, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Gambian Dalasi', 'code' => 'GMD', 'rate' => 70.409, 'symbol' => 'D', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Georgian Lari', 'code' => 'GEL', 'rate' => 2.743, 'symbol' => '₾', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Ghana Cedi', 'code' => 'GHS', 'rate' => 15.5, 'symbol' => '₵', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Gibraltar Pound', 'code' => 'GIP', 'rate' => 0.791, 'symbol' => '£', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Guatemala Quetzal(es)', 'code' => 'GTQ', 'rate' => 7.709, 'symbol' => 'Q', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Guinean Franc', 'code' => 'GNF', 'rate' => 8552.17, 'symbol' => 'FG', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Guyana Dollar', 'code' => 'GYD', 'rate' => 207.9, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Haiti Gourde', 'code' => 'HTG', 'rate' => 130.93, 'symbol' => 'G', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Honduras Lempira', 'code' => 'HNL', 'rate' => 24.957, 'symbol' => 'L', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'HongKong Dollar', 'code' => 'HKD', 'rate' => 7.782, 'symbol' => 'HK$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Hungary Forint', 'code' => 'HUF', 'rate' => 391.5, 'symbol' => 'Ft', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Iceland Krona', 'code' => 'ISK', 'rate' => 137.04, 'symbol' => 'kr', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Indonesia Rupiah', 'code' => 'IDR', 'rate' => 15930, 'symbol' => 'Rp', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Iranian Rial', 'code' => 'IRR', 'rate' => 512897, 'symbol' => '﷼', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Iraqi Dinar', 'code' => 'IQD', 'rate' => 1310, 'symbol' => 'ع.د', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Israel Shekel', 'code' => 'ILS', 'rate' => 3.647, 'symbol' => '₪', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Jamaican Dollar', 'code' => 'JMD', 'rate' => 157.347, 'symbol' => 'J$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Japanese Yen', 'code' => 'JPY', 'rate' => 151.42, 'symbol' => '¥', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Jordanian Dinar', 'code' => 'JOD', 'rate' => 0.708, 'symbol' => 'د.ا', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Kazakhstan Tenge', 'code' => 'KZT', 'rate' => 502.23, 'symbol' => '₸', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Kenyan Shilling', 'code' => 'KES', 'rate' => 129, 'symbol' => 'KSh', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Korean Won, North Korea', 'code' => 'KPW', 'rate' => 110, 'symbol' => '₩', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Korean Won, South Korea', 'code' => 'KRW', 'rate' => 1392.51, 'symbol' => '₩', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'rate' => 0.31, 'symbol' => 'د.ك', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Kyrgyzstan Som', 'code' => 'KGS', 'rate' => 86.25, 'symbol' => 'с', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Laos Kip', 'code' => 'LAK', 'rate' => 22020, 'symbol' => '₭', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Lebanese Pound', 'code' => 'LBP', 'rate' => 89500, 'symbol' => 'ل.ل', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Lesotho Loti', 'code' => 'LSL', 'rate' => 18.155, 'symbol' => 'M', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Liberian Dollar', 'code' => 'LRD', 'rate' => 179.389, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Libyan Dinar', 'code' => 'LYD', 'rate' => 4.894, 'symbol' => 'د.ل', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Macao Pataca', 'code' => 'MOP', 'rate' => 8.015, 'symbol' => 'P', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Malagasy Ariary', 'code' => 'MGA', 'rate' => 4667.74, 'symbol' => 'Ar', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Malawi Kwacha', 'code' => 'MWK', 'rate' => 1751, 'symbol' => 'MK', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Maldives Rufiyaa', 'code' => 'MVR', 'rate' => 15, 'symbol' => 'Rf', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Mauritania Ouguiya', 'code' => 'MRU', 'rate' => 39.77, 'symbol' => 'UM', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Mauritius Rupee', 'code' => 'MUR', 'rate' => 46.64, 'symbol' => '₨', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Mexican Peso', 'code' => 'MXN', 'rate' => 20.68, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Moldovan Leu', 'code' => 'MDL', 'rate' => 18.225, 'symbol' => 'L', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Mongolia Tugrik', 'code' => 'MNT', 'rate' => 3406, 'symbol' => '₮', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Morocco Dirham', 'code' => 'MAD', 'rate' => 10.004, 'symbol' => 'د.م.', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Mozambique Metical', 'code' => 'MZN', 'rate' => 63.25, 'symbol' => 'MT', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Myanmar Kyat', 'code' => 'MMK', 'rate' => 4100, 'symbol' => 'K', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Namibia Dollar', 'code' => 'NAD', 'rate' => 18.155, 'symbol' => 'N$', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Nepalese Rupee', 'code' => 'NPR', 'rate' => 135.109, 'symbol' => '₨', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Netherlands Antilles Guilder', 'code' => 'ANG', 'rate' => 1.79, 'symbol' => 'ƒ', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'CFP Franc', 'code' => 'XPF', 'rate' => 113.089, 'symbol' => '₣', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'New Zealand Dollar', 'code' => 'NZD', 'rate' => 1.694, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Nicaragua Cordoba Oro', 'code' => 'NIO', 'rate' => 36.55, 'symbol' => 'C$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Denar', 'code' => 'MKD', 'rate' => 58.11, 'symbol' => 'ден', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Norwegian Krone', 'code' => 'NOK', 'rate' => 11.072, 'symbol' => 'kr', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Pakistani Rupee', 'code' => 'PKR', 'rate' => 277.771, 'symbol' => '₨', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Panama Balboa', 'code' => 'PAB', 'rate' => 1, 'symbol' => 'B/.', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Kina', 'code' => 'PGK', 'rate' => 3.954, 'symbol' => 'K', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Paraguay Guarani', 'code' => 'PYG', 'rate' => 7804, 'symbol' => '₲', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Sol', 'code' => 'PEN', 'rate' => 3.758, 'symbol' => 'S/', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Philippine Peso', 'code' => 'PHP', 'rate' => 58.7, 'symbol' => '₱', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Poland Zloty', 'code' => 'PLN', 'rate' => 4.079, 'symbol' => 'zł', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Qatari Rial', 'code' => 'QAR', 'rate' => 3.646, 'symbol' => 'ر.ق.', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Romanian Leu', 'code' => 'RON', 'rate' => 4.715, 'symbol' => 'lei', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Russian Rouble', 'code' => 'RUB', 'rate' => 111.6, 'symbol' => '₽', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Rwanda Franc', 'code' => 'RWF', 'rate' => 1360.482, 'symbol' => 'FRw', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'St. Helena Pound', 'code' => 'SHP', 'rate' => 0.791, 'symbol' => '£', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Samoa Tala', 'code' => 'WST', 'rate' => 2.752, 'symbol' => 'T', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Sao Tome Principe Dobra', 'code' => 'STN', 'rate' => 23.277, 'symbol' => 'Db', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Saudi Riyal', 'code' => 'SAR', 'rate' => 3.75, 'symbol' => 'ر.س.', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'CFA Franc', 'code' => 'XOF', 'rate' => 621.642, 'symbol' => 'Fr', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Serbian Dinar', 'code' => 'RSD', 'rate' => 110.802, 'symbol' => 'дин.', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Seychelles Rupee', 'code' => 'SCR', 'rate' => 13.654, 'symbol' => '₨', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Sierra Leone Leone', 'code' => 'SLE', 'rate' => 23.39, 'symbol' => 'Le', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Singapore Dollar', 'code' => 'SGD', 'rate' => 1.342, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Solomon Is. Dollar', 'code' => 'SBD', 'rate' => 8.285, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Somali Shilling', 'code' => 'SOS', 'rate' => 24300, 'symbol' => 'S', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'South Africa Rand', 'code' => 'ZAR', 'rate' => 18.155, 'symbol' => 'R', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'South Sudanese Pound', 'code' => 'SSP', 'rate' => 3613.144, 'symbol' => 'SSP', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Sri Lanka Rupee', 'code' => 'LKR', 'rate' => 290.57, 'symbol' => 'Rs', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Sudanese Pound', 'code' => 'SDG', 'rate' => 1987, 'symbol' => 'ج.س.', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Surinamese Dollar', 'code' => 'SRD', 'rate' => 35.517, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Swedish Krona', 'code' => 'SEK', 'rate' => 10.918, 'symbol' => 'kr', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Swiss Franc', 'code' => 'CHF', 'rate' => 0.882, 'symbol' => 'CHF', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Syrian Pound', 'code' => 'SYP', 'rate' => 13600, 'symbol' => '£S', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Tajikistan Somoni', 'code' => 'TJS', 'rate' => 10.67, 'symbol' => 'SM', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Tanzania Shilling', 'code' => 'TZS', 'rate' => 2640, 'symbol' => 'TSh', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Thai Baht', 'code' => 'THB', 'rate' => 34.43, 'symbol' => '฿', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Tonga Pa\'anga', 'code' => 'TOP', 'rate' => 2.346, 'symbol' => 'T$', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'rate' => 6.754, 'symbol' => 'TT$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Tunisian Dinar', 'code' => 'TND', 'rate' => 3.146, 'symbol' => 'د.ت', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Turkish Lira', 'code' => 'TRY', 'rate' => 34.656, 'symbol' => '₺', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Turkmenistan Manat', 'code' => 'TMT', 'rate' => 3.5, 'symbol' => 'm', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Uganda Shilling', 'code' => 'UGX', 'rate' => 3682, 'symbol' => 'Sh', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Ukraine Hryvnia', 'code' => 'UAH', 'rate' => 41.5, 'symbol' => '₴', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'United Arab Emirates Dirham', 'code' => 'AED', 'rate' => 3.673, 'symbol' => 'د.إ', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'U.K. Pound', 'code' => 'GBP', 'rate' => 0.791, 'symbol' => '£', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Uruguay Peso', 'code' => 'UYU', 'rate' => 42.87, 'symbol' => '$', 'position' => 'left', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Uzbekistan Sum', 'code' => 'UZS', 'rate' => 12830, 'symbol' => 'сўм', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Vanuatu Vatu', 'code' => 'VUV', 'rate' => 117.74, 'symbol' => 'Vt', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Bolivar Digital', 'code' => 'VES', 'rate' => 46.327, 'symbol' => 'Bs.S', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Viet Nam Dong', 'code' => 'VND', 'rate' => 25384, 'symbol' => '₫', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Yemeni Rial', 'code' => 'YER', 'rate' => 528.74, 'symbol' => '﷼', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Zambia Kwacha', 'code' => 'ZMW', 'rate' => 27.324, 'symbol' => 'ZK', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()],
            ['name' => 'Zimbabwe Gold', 'code' => 'ZWG', 'rate' => 25.333, 'symbol' => 'ZWL', 'position' => 'right', 'status' => 1, 'is_default' => 0, 'created_at' => now(),'updated_at' => now()]
        ];

        Currency::insert($currencies);
    }
}
